apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # metadata.name的内容是由"复数名.分组名"构成，如下，clusteringressissuers是复数名，crd.xmh是分组名
  name: clusteringressissuers.crd.xmh
spec:
  # 分组名，在REST API中也会用到的，格式是: /apis/分组名/CRD版本
  group: crd.xmh   # 创建crd资源时，apiVersion字段的斜杠左边的内容
  # 支持的版本列表
  versions:
    - name: v1 # 创建crd资源时，apiVersion字段的斜杠右边的内容
      # 是否有效的开关.
      served: true
      # 只有一个版本能被标注为storage
      storage: true
      # 指定在kubectl-get时输出的列
      additionalPrinterColumns:
        - jsonPath: .spec.issuerName
          name: IssuerName
          type: string
      # 定义字段
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                  pattern: "^xmh-cii$" # 通过限定name实现单例模式
            spec:
              type: object
              properties:
                issuerName:
                  nullable: false
                  type: string

  # 范围是属于namespace或cluster的
  scope: Cluster
  names:
    # 复数名
    plural: clusteringressissuers
    # 单数名
    singular: clusteringressissuer
    # 类型名
    kind: ClusterIngressIssuer
    # 简称，就像service的简称是svc
    shortNames:
      - cii
